title:
  name: Title
  type: string
  default: Event-Participant Manager

title_short:
  name: Title (short)
  type: string
  default: EPM

email:
  name: Email
  type: string
  default: no-reply@example.com

admin:
  name: 'Admin role name'
  type: string
  default: admin

coordinator:
  name: 'Coordinator role name'
  type: string
  default: coordinator

participant:
  name: 'Participant role name'
  type: string
  default: participant